/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PunktDialog.java
 *
 * Created on 21.01.2010, 22:09:44
 */
package expert.kunkel.berge.gui;

import javax.swing.DefaultComboBoxModel;

import com.vividsolutions.jts.geom.Coordinate;
import com.vividsolutions.jts.geom.GeometryFactory;
import com.vividsolutions.jts.geom.Point;
import com.vividsolutions.jts.geom.impl.CoordinateArraySequence;

import expert.kunkel.berge.dao.jpa.DaoFactory;
import expert.kunkel.berge.dao.jpa.PunktDao;
import expert.kunkel.berge.dao.jpa.PunkttypDao;
import expert.kunkel.berge.model.Punkt;
import expert.kunkel.berge.model.Punkttyp;

/**
 *
 * @author thorsten
 */
public class PunktDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = -4622398212728411919L;
	private DefaultComboBoxModel punkttypCbModel = null;
	private static DaoFactory factory = DaoFactory.getInstance();
	private static PunkttypDao punkttypDao = factory.getPunkttypDAO();
	private static PunktDao punktDao = factory.getPunktDAO();
	private Punkt punkt = null;
	private boolean isNewPunkt = true;

	/** Creates new form PunktDialog */
	public PunktDialog(java.awt.Frame parent, Punkt punkt) {
		super(parent, true);

		punkttypCbModel = new DefaultComboBoxModel(punkttypDao.selectPunkttyp()
				.toArray());

		initComponents();

		if (punkt != null) {
			isNewPunkt = false;
			this.setData(punkt);
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		tfName = new javax.swing.JTextField();
		tfName2 = new javax.swing.JTextField();
		tfHoehe = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		taBeschreibung = new javax.swing.JTextArea();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		tfNord = new javax.swing.JTextField();
		tfOst = new javax.swing.JTextField();
		cbTyp = new javax.swing.JComboBox();
		tfUrl = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jLabel9 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Pukte erfassen");
		setLocationByPlatform(true);

		jLabel1.setText("Name");
		jLabel1.setName("jLabel1"); // NOI18N

		jLabel2.setText("Name 2");
		jLabel2.setName("jLabel2"); // NOI18N

		jLabel3.setText("Höhe");
		jLabel3.setName("jLabel3"); // NOI18N

		jLabel4.setText("Beschreibung");
		jLabel4.setName("jLabel4"); // NOI18N

		tfName.setName("tfName"); // NOI18N

		tfName2.setName("tfName2"); // NOI18N

		tfHoehe.setName("tfHoehe"); // NOI18N

		jScrollPane1.setName("jScrollPane1"); // NOI18N

		taBeschreibung.setColumns(20);
		taBeschreibung.setRows(5);
		taBeschreibung.setName("taBeschreibung"); // NOI18N
		jScrollPane1.setViewportView(taBeschreibung);

		jLabel5.setText("Nord");
		jLabel5.setName("jLabel5"); // NOI18N

		jLabel6.setText("Ost");
		jLabel6.setName("jLabel6"); // NOI18N

		jLabel7.setText("Typ");
		jLabel7.setName("jLabel7"); // NOI18N

		jLabel8.setText("URL");
		jLabel8.setName("jLabel8"); // NOI18N

		tfNord.setName("tfNord"); // NOI18N

		tfOst.setName("tfOst"); // NOI18N

		cbTyp.setMaximumRowCount(12);
		cbTyp.setModel(punkttypCbModel);
		cbTyp.setName("cbTyp"); // NOI18N

		tfUrl.setName("tfUrl"); // NOI18N

		jButton1.setText("OK");
		jButton1.setName("jButton1"); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okActionPerformed(evt);
			}
		});

		jButton2.setText("Leeren");
		jButton2.setName("jButton2"); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				leerenActionPerformed(evt);
			}
		});

		jButton3.setText("Abbrechen");
		jButton3.setName("jButton3"); // NOI18N
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				abbrechenActionPerformed(evt);
			}
		});

		jLabel9.setText("Meter");
		jLabel9.setName("jLabel9"); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel4)
																				.addComponent(
																						jLabel5)
																				.addComponent(
																						jLabel6)
																				.addComponent(
																						jLabel7)
																				.addComponent(
																						jLabel8)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel3))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						cbTyp,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jScrollPane1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						405,
																						Short.MAX_VALUE)
																				.addComponent(
																						tfUrl,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						405,
																						Short.MAX_VALUE)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																								.addComponent(
																										tfOst,
																										javax.swing.GroupLayout.Alignment.LEADING)
																								.addComponent(
																										tfNord,
																										javax.swing.GroupLayout.Alignment.LEADING,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										114,
																										Short.MAX_VALUE))
																				.addComponent(
																						tfName2,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						405,
																						Short.MAX_VALUE)
																				.addComponent(
																						tfName,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						405,
																						Short.MAX_VALUE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										tfHoehe,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										84,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jLabel9))))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jButton1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		147,
																		Short.MAX_VALUE)
																.addComponent(
																		jButton2)
																.addGap(129,
																		129,
																		129)
																.addComponent(
																		jButton3)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														tfName,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														tfName2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														tfHoehe,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel9))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel4)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														114,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(10, 10,
																		10)
																.addComponent(
																		jLabel5)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel6)
																				.addComponent(
																						tfOst,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel7)
																				.addComponent(
																						cbTyp,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel8)
																				.addComponent(
																						tfUrl,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		tfNord,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										21, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton2)
												.addComponent(jButton1)
												.addComponent(jButton3))
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void okActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_okActionPerformed
		// wenn es ein neuer Punkt ist
		if (isNewPunkt) {
			punkt = new Punkt();
		}
		punkt.setBeschreibung(taBeschreibung.getText());
		punkt.setHoehe(Integer.parseInt(tfHoehe.getText()));
		punkt.setName(tfName.getText());
		punkt.setName2(tfName2.getText());
		punkt.setTyp((Punkttyp) cbTyp.getSelectedItem());
		punkt.setUrl(tfUrl.getText());

		// jetzt noch den Punkt basteln
		Coordinate c = new Coordinate(Double.parseDouble(tfOst.getText()),
				Double.parseDouble(tfNord.getText()), Integer.parseInt(tfHoehe
						.getText()));
		CoordinateArraySequence cas = new CoordinateArraySequence(
				new Coordinate[] { c });
		Point point = new Point(cas, new GeometryFactory());
		punkt.setLage(point);

		// wenn es ein neuer Punkt ist
		if (isNewPunkt) {
			punktDao.insertPunkt(punkt);
		} // wenn es ein bestehender Punkt ist
		else {
			punktDao.updatePunkt(punkt);
		}

		((Berge) this.getParent()).reloadPunkte();

		this.setVisible(false);
	}// GEN-LAST:event_okActionPerformed

	private void leerenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_leerenActionPerformed
		this.clean();
	}// GEN-LAST:event_leerenActionPerformed

	private void abbrechenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_abbrechenActionPerformed
		this.setVisible(false);
	}// GEN-LAST:event_abbrechenActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			@Override
			public void run() {
				Punkt punkt = punktDao.findById(0);
				PunktDialog dialog = new PunktDialog(new javax.swing.JFrame(),
						punkt);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {

					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox cbTyp;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea taBeschreibung;
	private javax.swing.JTextField tfHoehe;
	private javax.swing.JTextField tfName;
	private javax.swing.JTextField tfName2;
	private javax.swing.JTextField tfNord;
	private javax.swing.JTextField tfOst;
	private javax.swing.JTextField tfUrl;

	// End of variables declaration//GEN-END:variables

	private void setData(Punkt punkt) {
		this.punkt = punkt;

		if (punkt != null) {
			if (punkt.getHoehe() != null) {
				tfHoehe.setText(Integer.toString(punkt.getHoehe()));
			} else {
				tfHoehe.setText("");
			}
			taBeschreibung.setText(punkt.getBeschreibung());
			tfName.setText(punkt.getName());
			tfName2.setText(punkt.getName2());
			tfNord.setText(Double.toString(punkt.getLage().getCoordinate().y));
			tfOst.setText(Double.toString(punkt.getLage().getCoordinate().x));
			tfUrl.setText(punkt.getUrl());

			cbTyp.setSelectedItem(punkt.getTyp());
		}
	}

	private void clean() {
		punkt = null;
		isNewPunkt = true;
		tfHoehe.setText("");
		taBeschreibung.setText("");
		tfName.setText("");
		tfName2.setText("");
		tfNord.setText("");
		tfOst.setText("");
		tfUrl.setText("");
		cbTyp.setSelectedIndex(6);
	}
}
