/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TourenabschnittDialog.java
 *
 * Created on 26.01.2010, 20:05:17
 */
package expert.kunkel.berge.gui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.TableColumn;

import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.autocomplete.ComboBoxCellEditor;

import expert.kunkel.berge.dao.DAOFactory;
import expert.kunkel.berge.dao.Punkt;
import expert.kunkel.berge.dao.PunktDAO;
import expert.kunkel.berge.dao.Tour;
import expert.kunkel.berge.dao.TourDAO;
import expert.kunkel.berge.dao.Tourabschnitt;
import expert.kunkel.berge.dao.TourabschnittDAO;
import expert.kunkel.berge.dao.Tourentag;

/**
 *
 * @author thorsten
 */
public class TourenabschnittDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = -284018233115431559L;
	private Tourentag ttag = null;
	private static DAOFactory factory = DAOFactory
			.getDAOFactory(DAOFactory.POSTGRESQL);
	private static TourabschnittDAO taDao = factory.getTourabschnittDAO();
	private static PunktDAO punktDao = factory.getPunktDAO();

	/** Creates new form TourenabschnittDialog */
	public TourenabschnittDialog(java.awt.Frame parent, Tourentag ttag) {
		super(parent, true);

		if (ttag == null) {
			JOptionPane.showMessageDialog(this,
					"Objekt Tour oder Tourentag fehlt!", "Fehler",
					JOptionPane.ERROR_MESSAGE);
			return;
		}

		this.ttag = ttag;

		initComponents();

		// hübsche Cell Renderer einbauen
		TableColumn punktColumn = tablePunkte.getColumnModel().getColumn(0);
		JComboBox<Punkt> comboBox = new JComboBox<>(new Vector<Punkt>(
				punktDao.selectPunkt()));
		comboBox.setEditable(true);
		AutoCompleteDecorator.decorate(comboBox);
		punktColumn.setCellEditor(new ComboBoxCellEditor(comboBox));

		List<Tourabschnitt> tas = null;
		try {
			tas = taDao.selectTourabschnitt(ttag);
		} catch (SQLException ex) {
			Logger.getLogger(TourenabschnittDialog.class.getName()).log(
					Level.SEVERE, null, ex);
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(TourenabschnittDialog.class.getName()).log(
					Level.SEVERE, null, ex);
		}

		for (int i = 0; i < tas.size(); i++) {
			Tourabschnitt ta = tas.get(i);
			tablePunkte.setValueAt(ta.getVonPunkt(), i, 0);
			tablePunkte.setValueAt(ta.getNachPunkt(), i + 1, 0);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		tablePunkte = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Tourenabschnitte bearbeiten");
		setLocationByPlatform(true);
		setModal(true);

		jScrollPane1.setName("jScrollPane1"); // NOI18N

		tablePunkte.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null }, { null }, { null }, { null },
						{ null }, { null }, { null }, { null }, { null },
						{ null }, { null }, { null }, { null }, { null },
						{ null }, { null }, { null }, { null }, { null },
						{ null } }, new String[] { "Punkt" }));
		tablePunkte.setName("tablePunkte"); // NOI18N
		jScrollPane1.setViewportView(tablePunkte);

		jButton1.setText("OK");
		jButton1.setName("jButton1"); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okActionPerformed(evt);
			}
		});

		jButton2.setText("Abbrechen");
		jButton2.setName("jButton2"); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				abbrechenActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														443, Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jButton1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		311,
																		Short.MAX_VALUE)
																.addComponent(
																		jButton2)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										410,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton2)
												.addComponent(jButton1))
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void abbrechenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_abbrechenActionPerformed
		this.setVisible(false);
	}// GEN-LAST:event_abbrechenActionPerformed

	private void okActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_okActionPerformed
		List<Punkt> punkte = new ArrayList<Punkt>();
		Punkt p = null;
		int i = 0;

		while ((p = (Punkt) tablePunkte.getValueAt(i, 0)) != null) {
			// System.out.println(p.toString());
			punkte.add(p);
			i++;
		}
		try {
			// zunächst die Tourenabschnitte löschen
			taDao.deleteTourabschnitt(ttag);
		} catch (SQLException ex) {
			Logger.getLogger(TourenabschnittDialog.class.getName()).log(
					Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(this, "Fehler beim Speichern!",
					"Fehler", JOptionPane.ERROR_MESSAGE);
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(TourenabschnittDialog.class.getName()).log(
					Level.SEVERE, null, ex);
		}

		// jetzt die Tourabschnitte speichern
		for (int j = 0; j < punkte.size() - 1; j++) {
			Punkt vonPunkt = punkte.get(j);
			Punkt nachPunkt = punkte.get(j + 1);

			Tourabschnitt ta = new Tourabschnitt();
			ta.setTtag(ttag);
			ta.setVonPunkt(vonPunkt);
			ta.setNachPunkt(nachPunkt);
			ta.setSequenz(j + 1);

			try {
				taDao.insertTourabschnitt(ta);
			} catch (SQLException ex) {
				Logger.getLogger(TourenabschnittDialog.class.getName()).log(
						Level.SEVERE, null, ex);
			} catch (ClassNotFoundException ex) {
				Logger.getLogger(TourenabschnittDialog.class.getName()).log(
						Level.SEVERE, null, ex);
			}
		}

		this.setVisible(false);
	}// GEN-LAST:event_okActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 * @throws UnsupportedLookAndFeelException
	 * @throws IllegalAccessException
	 * @throws InstantiationException
	 * @throws ClassNotFoundException
	 */
	public static void main(String args[]) throws ClassNotFoundException,
			InstantiationException, IllegalAccessException,
			UnsupportedLookAndFeelException {
		// System.setProperty("apple.laf.useScreenMenuBar", "true");
		// System.setProperty("com.apple.mrj.application.apple.menu.about.name",
		// "WikiTeX");
		// UIManager.setLookAndFeel(UIManager.ge());
		// UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");

		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				DAOFactory factory = DAOFactory
						.getDAOFactory(DAOFactory.POSTGRESQL);
				TourDAO tourDao = factory.getTourDAO();
				List<Tour> touren = tourDao.selectTour(1, null);
				TourenabschnittDialog dialog;
				try {
					dialog = new TourenabschnittDialog(
							new javax.swing.JFrame(), touren.get(0)
									.getTourentage().get(0));
					dialog.addWindowListener(new java.awt.event.WindowAdapter() {

						@Override
						public void windowClosing(java.awt.event.WindowEvent e) {
							System.exit(0);
						}
					});
					dialog.setVisible(true);
				} catch (SQLException ex) {
					Logger.getLogger(TourenabschnittDialog.class.getName())
							.log(Level.SEVERE, null, ex);
				} catch (ClassNotFoundException ex) {
					Logger.getLogger(TourenabschnittDialog.class.getName())
							.log(Level.SEVERE, null, ex);
				}
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tablePunkte;
	// End of variables declaration//GEN-END:variables
}
