/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TourentagDialog.java
 *
 * Created on 25.01.2010, 22:11:25
 */
package expert.kunkel.berge.gui;

import java.io.File;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

import expert.kunkel.berge.dao.DAOFactory;
import expert.kunkel.berge.dao.Region;
import expert.kunkel.berge.dao.Tour;
import expert.kunkel.berge.dao.TourDAO;
import expert.kunkel.berge.dao.Tourentag;
import expert.kunkel.berge.dao.TourentagDAO;
import expert.kunkel.berge.gui.model.RegionComboBoxModel;

/**
 *
 * @author thorsten
 */
public class TourentagDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = -7328448511087311436L;
	private SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
    private DefaultComboBoxModel regionCbModel = null;
    private Tourentag ttag = null;
    private DAOFactory factory = DAOFactory.getDAOFactory(DAOFactory.POSTGRESQL);
    private TourentagDAO ttagDao = factory.getTourentagDAO();

    /** Creates new form TourentagDialog */
    public TourentagDialog(java.awt.Frame parent, Tourentag ttag) {
        super(parent, true);

        if (ttag == null) {
            JOptionPane.showMessageDialog(this, "Erzeugen eines neuen Tourentages ist hier nicht erlaubt!",
                    "Fehler", JOptionPane.ERROR_MESSAGE);
        }

        regionCbModel = new RegionComboBoxModel();

        initComponents();

        try {
            this.setData(ttag);
        } catch (SQLException ex) {
            Logger.getLogger(TourDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TourDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        tfDatum.setEditable(false);

        tfTag.setEditable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfSchwierig = new javax.swing.JTextField();
        tfDatum = new javax.swing.JTextField();
        tfTag = new javax.swing.JTextField();
        tfAufstieg = new javax.swing.JTextField();
        tfAbstieg = new javax.swing.JTextField();
        tfGehzeit = new javax.swing.JTextField();
        cbRegion = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        taBeschreibung = new javax.swing.JTextArea();
        bOK = new javax.swing.JButton();
        bAbbrechen = new javax.swing.JButton();
        bAbschnitte = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfBilddatei = new javax.swing.JTextField();
        tfBildtitel = new javax.swing.JTextField();
        bAuswaehlen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tourentag bearbeiten");
        setLocationByPlatform(true);

        jLabel1.setText("Datum");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Tag in Tour");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Hm. Aufstieg");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Hm. Abstieg");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("Gehzeit");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("Bes. Schwierigkeiten");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText("Region");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText("Beschreibung");
        jLabel8.setName("jLabel8"); // NOI18N

        tfSchwierig.setName("tfSchwierig"); // NOI18N

        tfDatum.setName("tfDatum"); // NOI18N

        tfTag.setName("tfTag"); // NOI18N

        tfAufstieg.setName("tfAufstieg"); // NOI18N

        tfAbstieg.setName("tfAbstieg"); // NOI18N

        tfGehzeit.setName("tfGehzeit"); // NOI18N

        cbRegion.setModel(regionCbModel);
        cbRegion.setName("cbRegion"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        taBeschreibung.setColumns(20);
        taBeschreibung.setRows(5);
        taBeschreibung.setName("taBeschreibung"); // NOI18N
        taBeschreibung.setLineWrap(true);
        jScrollPane1.setViewportView(taBeschreibung);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        bOK.setText("OK");
        bOK.setName("bOK"); // NOI18N
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        bAbbrechen.setText("Abbrechen");
        bAbbrechen.setName("bAbbrechen"); // NOI18N
        bAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbbrechenActionPerformed(evt);
            }
        });

        bAbschnitte.setText("Tourenabschnitte bearbeiten");
        bAbschnitte.setName("bAbschnitte"); // NOI18N
        bAbschnitte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbschnitteActionPerformed(evt);
            }
        });

        jLabel9.setText("Bilddatei");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText("Bildtitel");
        jLabel10.setName("jLabel10"); // NOI18N

        tfBilddatei.setName("tfBilddatei"); // NOI18N

        tfBildtitel.setName("tfBildtitel"); // NOI18N

        bAuswaehlen.setText("Auswählen...");
        bAuswaehlen.setName("bAuswaehlen"); // NOI18N
        bAuswaehlen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAuswaehlenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addComponent(bAbschnitte)
                        .addGap(122, 122, 122)
                        .addComponent(bAbbrechen))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                            .addComponent(cbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSchwierig, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                            .addComponent(tfTag, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfGehzeit, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfAufstieg, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfAbstieg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                            .addComponent(tfBildtitel, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfBilddatei, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bAuswaehlen)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfAufstieg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAbstieg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfGehzeit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfSchwierig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfBilddatei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAuswaehlen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfBildtitel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOK)
                    .addComponent(bAbbrechen)
                    .addComponent(bAbschnitte))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
        // ändern der Daten
        ttag.setBeschreibung(taBeschreibung.getText());
        ttag.setGehzeit(tfGehzeit.getText());
        ttag.setHmAbstieg(tfAbstieg.getText());
        ttag.setHmAufstieg(tfAufstieg.getText());
        ttag.setSchwierigkeiten(tfSchwierig.getText());
        ttag.setBilddatei(tfBilddatei.getText());
        ttag.setBildttitel(tfBildtitel.getText());
        ttag.setRegion((Region) cbRegion.getSelectedItem());
        try {
            ttagDao.updateTourentag(ttag);
        } catch (SQLException ex) {
            Logger.getLogger(TourentagDialog.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Fehler beim Speichern!", "Fehler", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TourentagDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        ((Berge) this.getParent()).reloadTouren();

        this.setVisible(false);
}//GEN-LAST:event_bOKActionPerformed

    private void bAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbbrechenActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_bAbbrechenActionPerformed

    private void bAbschnitteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbschnitteActionPerformed
        TourenabschnittDialog taDialog = new TourenabschnittDialog((JFrame)this.getParent(), ttag);
        taDialog.setVisible(true);
    }//GEN-LAST:event_bAbschnitteActionPerformed

    private void bAuswaehlenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAuswaehlenActionPerformed
        JFileChooser jfc = new JFileChooser(new File(Berge.FOLDER_TOUREN));
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jfc.setMultiSelectionEnabled(false);
        jfc.showOpenDialog(this);
        if (jfc.getSelectedFile() == null) {
            return;
        }

        String fileName = jfc.getSelectedFile().getName();
        tfBilddatei.setText(fileName);
        tfBildtitel.setText(fileName.substring(0, fileName.lastIndexOf(".")));
    }//GEN-LAST:event_bAuswaehlenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DAOFactory factory = DAOFactory.getDAOFactory(DAOFactory.POSTGRESQL);
                TourDAO tourDao = factory.getTourDAO();
                List<Tour> touren = tourDao.selectTour(1, null);
                TourentagDialog dialog = null;
                try {
                    dialog = new TourentagDialog(new javax.swing.JFrame(), touren.get(0).getTourentage().get(0));
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TourentagDialog.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TourentagDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbbrechen;
    private javax.swing.JButton bAbschnitte;
    private javax.swing.JButton bAuswaehlen;
    private javax.swing.JButton bOK;
    private javax.swing.JComboBox cbRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taBeschreibung;
    private javax.swing.JTextField tfAbstieg;
    private javax.swing.JTextField tfAufstieg;
    private javax.swing.JTextField tfBilddatei;
    private javax.swing.JTextField tfBildtitel;
    private javax.swing.JTextField tfDatum;
    private javax.swing.JTextField tfGehzeit;
    private javax.swing.JTextField tfSchwierig;
    private javax.swing.JTextField tfTag;
    // End of variables declaration//GEN-END:variables

    private void setData(Tourentag ttag) throws SQLException, ClassNotFoundException {
        this.ttag = ttag;

        if (ttag != null) {
            tfDatum.setText(sdf.format(ttag.getDate()));
            tfAbstieg.setText(ttag.getHmAbstiegAsString());
            tfAufstieg.setText(ttag.getHmAufstiegAsString());
            tfGehzeit.setText(ttag.getGehzeitAsString());
            tfSchwierig.setText(ttag.getSchwierigkeiten());
            tfTag.setText(Integer.toString(ttag.getTag()));
            taBeschreibung.setText(ttag.getBeschreibung());
            cbRegion.getModel().setSelectedItem(ttag.getRegion());
            tfBilddatei.setText(ttag.getBilddatei());
            tfBildtitel.setText(ttag.getBildttitel());
        }
    }
}
